import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer"
import { montserrat } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`} >
        {children}
        <footer >
          <Footer />
        </footer>
      </body>
    </html>
  );
}
